replicaCount: 1

image:
  repository: vijay17700/go-web-app
  pullPolicy: IfNotPresent
  # Updated to the tag you verified is running (v1)
  tag: "25255606498"

service:
  type: LoadBalancer # Changed from ClusterIP so AWS creates a URL for you
  port: 80

# Keep your  check.. ingress as is if you are using an Ingress Controller, 
# but LoadBalancer is the "failsafe" way for your project demo.
ingress:
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: Prefix   